services:
  backend:
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"

